/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PmtCalendar {
    }
    interface PmtCalendarSubHeader {
    }
}
declare global {
    interface HTMLPmtCalendarElement extends Components.PmtCalendar, HTMLStencilElement {
    }
    var HTMLPmtCalendarElement: {
        prototype: HTMLPmtCalendarElement;
        new (): HTMLPmtCalendarElement;
    };
    interface HTMLPmtCalendarSubHeaderElement extends Components.PmtCalendarSubHeader, HTMLStencilElement {
    }
    var HTMLPmtCalendarSubHeaderElement: {
        prototype: HTMLPmtCalendarSubHeaderElement;
        new (): HTMLPmtCalendarSubHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "pmt-calendar": HTMLPmtCalendarElement;
        "pmt-calendar-sub-header": HTMLPmtCalendarSubHeaderElement;
    }
}
declare namespace LocalJSX {
    interface PmtCalendar {
    }
    interface PmtCalendarSubHeader {
    }
    interface IntrinsicElements {
        "pmt-calendar": PmtCalendar;
        "pmt-calendar-sub-header": PmtCalendarSubHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pmt-calendar": LocalJSX.PmtCalendar & JSXBase.HTMLAttributes<HTMLPmtCalendarElement>;
            "pmt-calendar-sub-header": LocalJSX.PmtCalendarSubHeader & JSXBase.HTMLAttributes<HTMLPmtCalendarSubHeaderElement>;
        }
    }
}
