/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PmtCalendar {
    }
    interface PmtMonthView {
        "currentDate": Date;
    }
}
declare global {
    interface HTMLPmtCalendarElement extends Components.PmtCalendar, HTMLStencilElement {
    }
    var HTMLPmtCalendarElement: {
        prototype: HTMLPmtCalendarElement;
        new (): HTMLPmtCalendarElement;
    };
    interface HTMLPmtMonthViewElement extends Components.PmtMonthView, HTMLStencilElement {
    }
    var HTMLPmtMonthViewElement: {
        prototype: HTMLPmtMonthViewElement;
        new (): HTMLPmtMonthViewElement;
    };
    interface HTMLElementTagNameMap {
        "pmt-calendar": HTMLPmtCalendarElement;
        "pmt-month-view": HTMLPmtMonthViewElement;
    }
}
declare namespace LocalJSX {
    interface PmtCalendar {
    }
    interface PmtMonthView {
        "currentDate"?: Date;
    }
    interface IntrinsicElements {
        "pmt-calendar": PmtCalendar;
        "pmt-month-view": PmtMonthView;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pmt-calendar": LocalJSX.PmtCalendar & JSXBase.HTMLAttributes<HTMLPmtCalendarElement>;
            "pmt-month-view": LocalJSX.PmtMonthView & JSXBase.HTMLAttributes<HTMLPmtMonthViewElement>;
        }
    }
}
