/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PmtCalendar {
    }
    interface PmtCalendarHeader {
    }
}
declare global {
    interface HTMLPmtCalendarElement extends Components.PmtCalendar, HTMLStencilElement {
    }
    var HTMLPmtCalendarElement: {
        prototype: HTMLPmtCalendarElement;
        new (): HTMLPmtCalendarElement;
    };
    interface HTMLPmtCalendarHeaderElement extends Components.PmtCalendarHeader, HTMLStencilElement {
    }
    var HTMLPmtCalendarHeaderElement: {
        prototype: HTMLPmtCalendarHeaderElement;
        new (): HTMLPmtCalendarHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "pmt-calendar": HTMLPmtCalendarElement;
        "pmt-calendar-header": HTMLPmtCalendarHeaderElement;
    }
}
declare namespace LocalJSX {
    interface PmtCalendar {
    }
    interface PmtCalendarHeader {
    }
    interface IntrinsicElements {
        "pmt-calendar": PmtCalendar;
        "pmt-calendar-header": PmtCalendarHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pmt-calendar": LocalJSX.PmtCalendar & JSXBase.HTMLAttributes<HTMLPmtCalendarElement>;
            "pmt-calendar-header": LocalJSX.PmtCalendarHeader & JSXBase.HTMLAttributes<HTMLPmtCalendarHeaderElement>;
        }
    }
}
