// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pmt.FantalyticApi.Models;

#nullable disable

namespace Pmt.FantalyticApi.Migrations
{
    [DbContext(typeof(FantalyticContext))]
    [Migration("20220905172047_2022-09-05-1308")]
    partial class _202209051308
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pmt.FantalyticApi.Models.QB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Ints")
                        .HasColumnType("integer");

                    b.Property<int>("PassingYds")
                        .HasColumnType("integer");

                    b.Property<float>("PassingYdsPerAttempt")
                        .HasColumnType("real");

                    b.Property<string>("Player")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TDs")
                        .HasColumnType("integer");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("QBs");
                });

            modelBuilder.Entity("Pmt.FantalyticApi.Models.RB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Player")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RushingYds")
                        .HasColumnType("integer");

                    b.Property<int>("rushAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("rushing20Yds")
                        .HasColumnType("integer");

                    b.Property<int>("rushingTds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RBs");
                });
#pragma warning restore 612, 618
        }
    }
}
