export enum CardType {
  CLINICAL_SUPERVISION,
  INDIVIDUAL_COUPLE,
  TELEHEALTH,
  HOW_CAN_IT_HELP,
  DO_I_NEED_IT,
  WHY_DO_PEOPLE_GO,
  WHAT_IS_IT_LIKE,
  MEDICATION_VS_PSYCHOTHERAPY,
  DO_YOU_TAKE_INSURANCE,
  IS_IT_CONFIDENTIAL,
}

export default CardType;
