# Download Microsoft SDK container
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine as build

WORKDIR /pmt-auth

COPY ./*.csproj .
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

#Download Microsoft runtime container
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine as runtime

WORKDIR /pmt-auth

COPY --from=build /pmt-auth/out .

EXPOSE 80

ENTRYPOINT [ "dotnet", "pmt-auth.dll" ]